### ISSUE TITLE
We need a test for negative maximum profitability

### ISSUE THREAD

**Issue by smmaurer** [ual/bayarea_urbansim#2]
I'm still in the process of tracking this down, but in at least one case the np.random.choice() error is triggered by the feasibility model step producing negative maximum profitabilities for certain projects, which then become negative weights for those projects being chosen in the developer model step.

We need to fix whatever is causing this, and add tests for negative profitability!

Environment: OS X, latest pandas and numpy, latest udst/urbansim, latest ual/urbansim_defaults (master branch), latest ual/bayarea_urbansim (ual-development branch).

Below is the error output from run.py, in the first year of model iterations. 

To get the extra describe() output,  i added the following lines to urabansim/urbansim/developer/developer.py at line199:
````
        print df.max_profit.describe()
        print df.parcel_size.describe()
        print df.max_profit_per_size.describe()
````

````
Running step 'residential_developer'
Using default limits
Number of agents: 2,609,000
Number of agent spaces: 2,814,972
Current vacancy = 0.07
Target vacancy = 0.03, target of new units = 0
Running developer for none with target of 0
Number of agents: 2,609,000
Number of agent spaces: 2,814,972
Current vacancy = 0.07
Target vacancy = 0.03, target of new units = 0
96,034 feasible buildings before running developer
Sum of net units that are profitable: 1,759,921

count    6.074900e+04
mean     1.127165e+07
std      9.606498e+07
min     -5.805876e+06
25%      4.690750e+05
50%      1.376752e+06
75%      4.792581e+06
max      1.194421e+10
Name: max_profit, dtype: float64

count    6.074900e+04
mean     1.432919e+05
std      7.615294e+05
min      1.755889e+02
25%      6.203466e+03
50%      1.348141e+04
75%      6.131482e+04
max      3.001519e+07
Name: parcel_size, dtype: float64

count    60749.000000
mean       220.162068
std        438.770497
min       -240.898567
25%         26.843423
50%         80.063768
75%        216.804512
max       5257.080000
Name: max_profit_per_size, dtype: float64

Traceback (most recent call last):
  File "run.py", line 225, in <module>
    run_models(MODE, SCENARIO)
  File "run.py", line 142, in run_models
    orca.run(models, iter_vars=years_to_run)
  File "/Users/smmaurer/anaconda/lib/python2.7/site-packages/orca/orca.py", line 1876, in run
    step()
  File "/Users/smmaurer/anaconda/lib/python2.7/site-packages/orca/orca.py", line 780, in __call__
    return self._func(**kwargs)
  File "/Users/smmaurer/Dropbox/Git-rMBP/ual/bayarea_urbansim/baus/models.py", line 312, in residential_developer
    **kwargs)
  File "/Users/smmaurer/Dropbox/Git-rMBP/ual/urbansim_defaults/urbansim_defaults/utils.py", line 781, in run_developer
    bldg_sqft_per_job=bldg_sqft_per_job)
  File "/Users/smmaurer/Dropbox/Git-rMBP/ual/urbansim/urbansim/developer/developer.py", line 203, in pick
    df.max_profit_per_size.sum()))
  File "mtrand.pyx", line 1415, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:15926)
ValueError: probabilities are not non-negative
None
Traceback (most recent call last):
  File "run.py", line 235, in <module>
    raise e
ValueError: probabilities are not non-negative
Closing remaining open files:./data/2015_09_01_bayarea_v3.h5...done./data/2015_06_01_osm_bayarea4326.h5...done./data/2015_08_03_tmnet.h5...done
````

**Comment by smmaurer** [comment]
Fletcher reports that negative profitability in and of itself is not a bug, because this is sometimes used to rank projects that will be subsidized. But these projects need to be filtered out before the negative profitabilities are used as weights in a choice function. 

In the meantime, Fletcher has a 'return-on-cost' branch of urbansim, which uses cost rather than profitability for the weightings. This seems to solve the error I described above.

**Comment by waddell** [comment]
My last run failed in 2040 in developer_reprocess apparently related to this error.  I'm triple-checking that I have the same branches and all up to date. Will run it again to see if it might be just random variation.

What is really weird is that it is on the choice from this probability distribution: p=(res_units/res_units.sum()).

Not obvious how res_units could be negative?  I'm adding a print statement to check it as well.

**Comment by waddell** [comment]
Just got a run to finish through 2040 without crashing.

**Comment by smmaurer** [comment]
The functionality for specifying project weights has been moved from the 'return-on-cost' branch into the release version of udst/urbansim, so this particular error should not show up any more. https://github.com/UDST/urbansim/pull/172

Additionally, the orca_test framework now allows us to easily specify runtime tests for problematic outcomes (like negative profitability). https://github.com/urbansim/orca_test
